services:
  # Next.js web application
  - type: web
    name: omuscle-web
    runtime: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_SOCKET_URL
        value: https://omuscle-socket.onrender.com
      - key: PORT
        value: 10000
  
  # Socket.io server
  - type: web
    name: omuscle-socket
    runtime: node
    buildCommand: npm install
    startCommand: node socket-server/index.mjs
    envVars:
      - key: PORT
        value: 10000
